### ISSUE TITLE
MagicDesk compatibility

### ISSUE THREAD

**Issue by r1me** [Zibri/C64-1541-Speed-Test#1]
I've tried to add this tool to my utilities cartridge in MagicDesk format, however the 1541-II CPU jams:
![magicdesk_1541speed_test](https://user-images.githubusercontent.com/13695767/89683447-d7aab780-d8f8-11ea-9262-4c0087ce583b.png)
Example cartridge file:
[magicdesk_C64-1541-Speed-Test.zip](https://github.com/Zibri/C64-1541-Speed-Test/files/5043412/magicdesk_C64-1541-Speed-Test.zip)
By any chance is this fixable ?

**Comment by Zibri** [comment]
Does it work if you press "8" before pressing any other function key?

**Comment by Zibri** [comment]
I have not much experience with cartridges. :(

**Comment by Zibri** [comment]
Do this:

load"rpm",8
**poke 2073,255**
save "rpmc",8

then make the cartridge from RPMC program.

I see you made the cartridge from an old version. **Please download the latest version** from [HERE](https://github.com/Zibri/C64-1541-Speed-Test/blob/master/rpm.prg?raw=true) then load it, do the poke and save it. That will work 100%
In the (old) version you used, the poke is: poke 2074,255 but I **suggest** you to use the latest version just to be sure.
I just checked and it works in VICE.

**Comment by Zibri** [comment]
also, the program start address is $80d (2061)  the cart should start it there.

**Comment by Zibri** [comment]
I see you made the cartridge from an old version. Please download the latest version from [HERE](https://github.com/Zibri/C64-1541-Speed-Test/blob/master/rpm.prg?raw=true) then load it, do the poke and save it. That will work 100%

**Comment by Zibri** [comment]
In the (old) version you used the poke is: poke 2074,255   but I suggest you to use the latest version just to be sure.
I just checked and it works in VICE.
